FROM python:3.11-slim

WORKDIR /tmra-tool

COPY . /tmra-tool

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8501

ENTRYPOINT ["streamlit", "run", "streamlit_gui.py", "--server.port=8501", "--server.address=0.0.0.0"]